import express from 'express';
import counsellorRoutes from './counsellor.route.js';
import supervisorRoutes from './supervisor.route.js';
import analyserRoutes from './analyser.route.js';
import studentRoutes from './student.route.js';
import leadActivityRoutes from './leadactivity.route.js';
import leadassignmentl2Routes from './leadassignment.route.js';
import leadassignmentl3Routes from './leadassignmentl3.route.js';
import universitycoursesRoutes from './universitycourse.route.js';
import remarkRoutes from './remark.route.js';
import studentcoursestatusRoutes from './studentcoursestatus.route.js';
import StudentCourseStatusLogsRoutes from './StudentCourseStatusLogs.route.js';
import filterOptionRoutes from './filterOptionRoute.route.js';
import templateRoutes from './template.route.js';
import whatsappRoute from './watsaapchat.route.js';
import webhookRoutes from './ivr/webhook.route.js';
import courseHeaderValuesRoutes from './universityheader.route.js';
import studentCollegeCredsRoutes from './studentCollegeCreds.routes.js';
import courseHeaderRoutes from './universityheadervalues.route.js';
import scoreboardRoutes from './scoreboard.route.js';
import collegeCrmRoutes from './ads/CollegeCrmRoute.js';
import collegeApiSentStatus from './collegeApiSentStatus.route.js';
import metaAdsRoutes from './ads/MetaAdsRoutes.js';
import googleAdsRoutes from './ads/Google_ads_Routes.js';
import WishlistRouter from './WishListStudent.route.js';
import Webhook from '../auto_deploy/main.js';
import Campaign from './campaign.routes.js';
import websiteChatRoutes from './websiteChat.route.js';
import univeristyBrochureRoutes from './universityBrochure.route.js';
import StudentReassignmentLogic from './student_reassignment_logic.route.js';
import secondaryStudentRoutes from './studentInfo.route.js';

const router = express.Router();

router.use('/counsellor', counsellorRoutes);
router.use('/supervisor', supervisorRoutes);
router.use('/analyser', analyserRoutes);
router.use('/student', studentRoutes);
router.use('/leadactivity', leadActivityRoutes);
router.use('/leadassignmentl2', leadassignmentl2Routes);
router.use('/leadassignmentl3', leadassignmentl3Routes);
router.use('/universitycourse', universitycoursesRoutes);
router.use('/remark', remarkRoutes);
router.use('/studentcoursestatus', studentcoursestatusRoutes);
router.use('/StudentCourseStatusLogs', StudentCourseStatusLogsRoutes);
router.use('/filterOption', filterOptionRoutes);
router.use('/templates', templateRoutes);
router.use('/whatsapp', whatsappRoute);
router.use('/webhook', webhookRoutes);
router.use('/courseHeaderValue', courseHeaderRoutes);
router.use('/courseHeader', courseHeaderValuesRoutes);
router.use('/scoreboard', scoreboardRoutes);
router.use('/studentCollegeCreds', studentCollegeCredsRoutes);
router.use('/collegeapisentStatus', collegeApiSentStatus);
router.use('/wishlist', WishlistRouter);
router.use('/ads', googleAdsRoutes);
router.use('/auto-deploy', Webhook);
router.use('/campaigns', Campaign);
router.use('/website-chat', websiteChatRoutes);
router.use('/universitytemplates', univeristyBrochureRoutes);
router.use('/student-reassignment-logic', StudentReassignmentLogic);
router.use('/secondaryStudentInfo', secondaryStudentRoutes);
router.use('/api/crm', collegeCrmRoutes);
router.use('/api/meta-ads', metaAdsRoutes);

export default router;
